id: P4ED43490
initial_creation_type: input
source_metadata:
  title: Patrul Rinpoche Series
  language: en
  description: 'Texts by and about the great Rimé master, Dza Patrul Orgyen Jigme
    Chökyi Wangpo (rdza dpal sprul o rgyan ''jigs med chos kyi dbang po, 1808–1887):'
  volume:
    c7bf1e33b03145b284260dae4f9690d5:
      title: Advice for Alak Dongak
      parent: Advice
    7e38aca5f52f41f6a3862a7d3a9eb1c8:
      title: Advice to Lama Rigdzin Gyatso on Understanding the Influence of Companions
        and Avoiding and Adopting Them Accordingly
      parent: Advice
    41792fed810a441286048f2032b574a5:
      title: Nine Considerations and Criteria for Benefiting Beings
      parent: Advice
    5d9a087ad29e425ca3e79439b566bfd0:
      title: The Precious Treasury of Written Instruction Transmitted One-to-One
      parent: Advice
    b3479d14abf446f7b8265688cd00bc6d:
      title: Yearning for Mountain Solitude
      parent: Advice
    21afb8dbdb14406eaa0f61cf67a0a779:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration Prayers
    980f9f2617d7458f8ff96cf189669fae:
      title: Biography of Patrul Rinpoche
      parent: Biography
    f516023eb0e54b138fa22da2fa83e3d0:
      title: Prayer to the Lineage of the Bodhicaryāvatāra
      parent: Bodhicaryāvatāra
    62fcd47273914925acd26db3c94758e5:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    c7041a5c273c41fabcfbb72791e55a02:
      title: A Brief Guide to the Stages and Paths of the Bodhisattvas
      parent: Buddhist Philosophy & Teachings
    be4a51bfa67b4a779ff7f1dac3d9c9ac:
      title: A Brief Introduction to the Bardos
      parent: Buddhist Philosophy & Teachings
    f97ccd7d71c84beb864bdeb613c6ad33:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Buddhist Philosophy & Teachings
    97e07b674fc94bc991d7d6908a3bfbd5:
      title: An Instruction on the View of the Mahāyāna – Clarifying the Two Truths
      parent: Buddhist Philosophy & Teachings
    9ad70c7798bf46598d0d25756813d2ad:
      title: Preliminary Points to be Explained When Teaching the Buddha's Word or
        the Treatises
      parent: Buddhist Philosophy & Teachings
    d0650ccd97764f0c9e17cf25e1a780b4:
      title: 'The Concentrated Seed: How to Distinguish the Tenets of Non-Buddhist
        and Buddhist Schools'
      parent: Buddhist Philosophy & Teachings
    200f584464874435b96fa936a587a5fe:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Dzogchen
    7bacd64026654587959b4a9d499a21a5:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Dzogchen
    4053837c5a324f78bd2c7745cb2c9567:
      title: Brief Guide to the Stages of Visualization for the Ngöndro Practice
      parent: Ngöndro
    31c4e703ded84418aaef85ec752fe96f:
      title: 'A Garland of Fresh Utpala Flowers: A Brief Synopsis of the Treasury
        of Precious Qualities, A Treatise of Pith Instructions'
      parent: Pedagogy
    d692caa4dfe34c42a7f05f5058208d81:
      title: 'Mirror of the Mind: Prologue to The Treasury of Precious Qualities'
      parent: Pedagogy
    25f3841422a14866a065711de213dab3:
      title: In Praise of Glorious Vajrasattva
      parent: Praise
    8e628cb0a30a4088bdbe8c4763c16f0a:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Praise
    71d414fb10f142e78df6ae01aea630dc:
      title: 'Excellent Explanation from the Scriptural Tradition: A Brief Guide to
        the Stages of Meditating on the General Themes of the Ornament to the Prajñāpāramitā'
      parent: Prajñāpāramitā
    d8fcb2c474ee4b0d9d875624fb7882be:
      title: 'Nectar of Lunar Crystal: A Prayer to Orgyen Chökyi Wangpo'
      parent: Prayers
    359fce89a3e34b8d9280fadbf90f2f00:
      title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
      parent: Prayers
    fc9d6e69959246069c88ceabcb75b967:
      title: Prayer to Machik Labdrön
      parent: Prayers
    01bdebdcf91f46769fe0bbd293d502c1:
      title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
      parent: Prayers
    910aa403398446f792b45fe165406570:
      title: Brief Windhorse Practice of Tārā
      parent: Prayers & Practices
    b7b2145d62e34d5d8f1185f6d011e316:
      title: Temple Dedication Prayer
      parent: Prayers & Practices
    a999f2e2bcb64f63bf793ef07537e7bd:
      title: A Brief Mañjuśrī Sādhana
      parent: Sādhanas
    c26b31163d6143058d1b2429f20ce2be:
      title: The Method for Observing the Eight-Branched One-Day Vow
      parent: Sojong
    b4e201c238e04421a7b432e52b16dfc1:
      title: The Special Teaching of the Wise and Glorious King – Commentary
      parent: Special Teaching of the Wise and Glorious King
    8bf36d629a744c9ba9fb6879c5318a79:
      title: The Special Teaching of the Wise and Glorious King—Root Text
      parent: Special Teaching of the Wise and Glorious King
    e99ba338d0774c61afdd582510f0aa9b:
      title: The Special Teaching of the Wise and Glorious King—Root Text (arranged
        in Tibetan-English verses)
      parent: Special Teaching of the Wise and Glorious King
    b7f81c41cc8947d08a3f2b6157e88f3c:
      title: A Topical Outline of the General Confession Spoken by the Five Great
        Sages
      parent: Topical Outlines
    b200ff7ada9144d29cff0eb30bd22390:
      title: The Way to Explain the King of All Aspiration Prayers, the Secret Vajra
        Knot
      parent: Topical Outlines
    320eddbc5897423daa186f626c7a990a:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Topical Outlines
    ca51b67548f8451c83e54755e6d6f8fa:
      title: 'Transference: Enlightenment Without Meditation (Compilation)'
      parent: Transference (Phowa)
    7e381c44a40f4807a802b2f4b6af6cca:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-03-01T01:13:56.739637'
last_modified_at: '2022-03-01T01:13:56.739644'
